/**
 * https://leetcode.com/problems/find-the-difference/
 * 
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * 
 * Input: s = "a", t = "aa"
 * Output: "a"
 */
public class FindTheDifference389 {
    public static void main(String[] args) {
        FindTheDifference389 main = new FindTheDifference389();
        main.findTheDifference("a", "aa");
    }

    public char findTheDifference(String s, String t) {
        int[] sArr = new int[26];
        int[] tArr = new int[26];
        for (char c : s.toCharArray()) {
            sArr[c - 'a']++;
        }
        for (char c : t.toCharArray()) {
            tArr[c - 'a']++;
        }
        for (char c : t.toCharArray()) {
            if (tArr[c - 'a'] > sArr[c - 'a']) {
                return c;
            }
        }
        return 'a';
    }
}
